Feat/hot keys
webjs-tech/react-dash-player pull request #26
Opened 2023-08-07 11:55 UTC by EdPrys

Fix: #8 
add: hot-keys

2023-08-07 13:10 UTC, Security2431 requested changes
Looks good, left some comments. Also, please, can you base this PR on main branch? Otherwise, we cannot merge it, before other PRs merged

2023-08-07 13:10 UTC, Security2431 commented on common/utils/hotKeys.ts
> +          videoEl.currentTime = videoEl.currentTime + 5;
it scrolls on 14s 🤔 Can you figure out?

2023-08-07 13:10 UTC, Security2431 commented on common/utils/hotKeys.ts
> +          videoEl.currentTime = Math.max(videoEl.currentTime - 5, 0);
it scrolls on 14s 🤔 Can you figure out?

2023-08-07 13:10 UTC, Security2431 commented on common/utils/hotKeys.ts
> +          videoEl.currentTime = Math.max(videoEl.currentTime - 5, 0);
Try to scroll at the end video

2023-08-07 13:10 UTC, Security2431 commented on common/utils/hotKeys.ts
> +          // navigateNext()
please add comment what this hot key should do

2023-08-07 13:10 UTC, Security2431 commented on common/utils/hotKeys.ts
> +          break;
What this hotkey should do?

2023-08-07 13:10 UTC, Security2431 commented on common/utils/hotKeys.ts
> +          videoEl.currentTime = Math.max(videoEl.currentTime - 5, 0);
At the beginning video it scrolls by 5s, but then by 14s

2023-08-07 13:14 UTC, EdPrys commented on common/utils/hotKeys.ts
> +          break;
turn subtitles on and off

2023-08-07 13:18 UTC, Security2431 commented on common/utils/hotKeys.ts
> +          if (videoEl instanceof HTMLVideoElement) {
```suggestion
          // Show/hide subtitles
          if (videoEl instanceof HTMLVideoElement) {
```

2023-08-08 07:20 UTC, Security2431 commented on common/utils/hotKeys.ts
> +          videoEl.currentTime = videoEl.currentTime + 5;
Created separate issue #28

2023-08-08 07:21 UTC, Security2431 commented on common/utils/hotKeys.ts
> +          videoEl.currentTime = Math.max(videoEl.currentTime - 5, 0);
Moved this to separate issue #28

2023-08-08 07:40 UTC, Security2431 commented on components/VideoPlayer/VideoPlayer.tsx
> +        setupHotKeys(videoRef.current!);
If you want clarify, feel free to ping me

2023-08-08 10:09 UTC, merged